server:
  port: 8080

directories:
  staticAssets: './assets/'
  templates: './templates/'
  data: './data/list.json'
  plugin: './data/plugins/'
  serverSetting: './settings/serverSettings.json'
  userSetting: './data/userSettings.json'
  script: './scripts/'
